// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Lydia's Memories",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Lydia's Memories",
            targets: ["AppModule"],
            bundleIdentifier: "com.Gabriel.LydiasMemories",
            teamIdentifier: "BNMNXQ97LQ",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .landscapeRight
            ],
            appCategory: .games
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)